import React from "react";
import ReactDOM, { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
const root1 = document.querySelector("#root1");
const root2 = document.querySelector("#root2");
const Head = ReactDOM.createRoot(root1);
const container = ReactDOM.createRoot(root2);
container.render(<App />);
Head.render(<h1 className="Heading">My Top Netflix Picks</h1>);
